# Generated by Django 4.1.7 on 2023-02-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
